-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_function is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_a_soma : IN STD_LOGIC_VECTOR (31 downto 0);
    input_b_soma : IN STD_LOGIC_VECTOR (31 downto 0);
    input_a_sub : IN STD_LOGIC_VECTOR (31 downto 0);
    input_b_sub : IN STD_LOGIC_VECTOR (31 downto 0);
    output_soma : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_soma_ap_vld : OUT STD_LOGIC;
    output_subtracao : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_subtracao_ap_vld : OUT STD_LOGIC;
    ap_rst : IN STD_LOGIC );
end;


architecture behav of top_function is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_function_top_function,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.552000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=78,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_ce_reg : STD_LOGIC;


begin



    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    output_soma <= std_logic_vector(unsigned(input_b_soma) + unsigned(input_a_soma));

    output_soma_ap_vld_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            output_soma_ap_vld <= ap_const_logic_1;
        else 
            output_soma_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_subtracao <= std_logic_vector(unsigned(input_a_sub) - unsigned(input_b_sub));

    output_subtracao_ap_vld_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            output_subtracao_ap_vld <= ap_const_logic_1;
        else 
            output_subtracao_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
